# -*- coding: utf-8 -*-
"""Project_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fWqmrtllQtnD-011KadCfHNETDEbet2J
"""

l = []
with open("student.csv","r") as rd:

  lines = rd.readlines()
  data_lines = lines[1:]
  for i in data_lines:
    l.append(i)

print(l)

rec = []
for j in l:
  clean_line = j.strip()
  values = clean_line.split(",")
  rec.append(values)

print(rec)

class Student:
    def __init__(self, roll_no, name, maths, physics, chemistry, english):
        self.roll_no = int(roll_no)
        self.name = name
        self.marks = {
            'maths': int(maths),
            'physics': int(physics),
            'chemistry': int(chemistry),
            'english': int(english)
             }

students = []

for values in rec:
    s = Student(
        values[0],
        values[1],
        values[2],
        values[3],
        values[4],
        values[5]
    )
    students.append(s)

for s in students:
    print(s.name, s.marks)

subjects = ['maths', 'physics', 'chemistry', 'english']

number_of_students = len(students)
for subject in subjects:
    total = 0
    for student in students:
        total += student.marks[subject]
    average = total / number_of_students
    print(subject, average)

subjects = ['maths', 'physics', 'chemistry', 'english']
number_of_subjects = len(subjects)

for student in students:
  total = 0
  for subject in subjects:
    total += student.marks[subject]

  average = total / number_of_subjects
  print(student.name, average)

highest_avg = 0
top_student = None

for student in students:
    total = 0
    for subject in subjects:
        total += student.marks[subject]

    avg = total / number_of_subjects

    if avg > highest_avg:
        highest_avg = avg
        top_student = student

print("Top Performer:", top_student.name, highest_avg)

pass_students = 0
fail_students = 0

for student in students:
    if all(mark >= 40 for mark in student.marks.values()):
        pass_students += 1
    else:
        fail_students += 1

print("No of students Passed:", pass_students)
print("No of students Failed:", fail_students)

with open("student_performance_report.txt", "w") as f:
    f.write("STUDENT PERFORMANCE ANALYSIS REPORT\n")
    f.write("----------------------------------\n\n")
    f.write("Subject-wise Average Marks:\n\n")

    for subject in subjects:
        total = 0
        for student in students:
            total += student.marks[subject]
        average = total / len(students)
        f.write(f"{subject.capitalize()}: {average:.2f}\n")

    f.write("\n")

    f.write("Student-wise Average Marks:\n\n")

    for student in students:
        total = 0
        for subject in subjects:
            total += student.marks[subject]
        average = total / len(subjects)
        f.write(f"{student.name}: {average:.2f}\n")

    f.write("\n")

    top_student = students[0]
    top_avg = 0

    for student in students:
        total = 0
        for subject in subjects:
            total += student.marks[subject]
        avg = total / len(subjects)

        if avg > top_avg:
            top_avg = avg
            top_student = student

    f.write(f"Top Performer: {top_student.name} ({top_avg})\n\n")

    f.write("Pass / Fail Summary:\n")

    for student in students:
        pass_count = 0
        fail_count = 0

        for subject in subjects:
            if student.marks[subject] >= 40:
                pass_count += 1
            else:
                fail_count += 1

        f.write(f"{student.name}: Pass = {pass_count}, Fail = {fail_count}\n")

from google.colab import drive
drive.mount('/content/drive')

with open("student_performance_report.txt","r")as rd:
  print(rd.read())